version: '3.9'
services:
  redismaster1:
    image: redis
    container_name: redismaster1
    restart: always
    command:
      - /bin/bash 
      - -c 
      - |
        redis-server /usr/local/etc/redis/redis-master1.conf
        redis-server /usr/local/etc/redis/sentinel-master1.conf --sentinel
    ports:
      - 16382:6379
      - 36379:26379
    volumes:
      - /data/docker/redis/sentinel/master1:/data
      - /root/sources/manifests/redis/redis-conf:/usr/local/etc/redis
    environment:
      TZ: "Asia/Shanghai"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 50M
    networks:
      default:
        ipv4_address: "172.18.1.5"
 
  redisslave1:
    image: redis
    container_name: redisslave1
    depends_on:
      - redismaster1
    restart: always
    command:
      - /bin/bash 
      - -c 
      - |
        redis-server /usr/local/etc/redis/redis-slave1.conf
        redis-server /usr/local/etc/redis/sentinel-slave1.conf --sentinel
    ports:
      - 16383:6379
      - 36380:26379
    volumes:
      - /data/docker/redis/sentinel/slave1:/data
      - /root/sources/manifests/redis/redis-conf:/usr/local/etc/redis
    environment:
      TZ: "Asia/Shanghai"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 50M
    networks:
      default:
        ipv4_address: "172.18.1.6"

  redisslave2:
    image: redis
    container_name: redisslave2
    depends_on:
      - redismaster1
    restart: always
    command:
      - /bin/bash 
      - -c 
      - |
        redis-server /usr/local/etc/redis/redis-slave2.conf
        redis-server /usr/local/etc/redis/sentinel-slave2.conf --sentinel
    ports:
      - 16384:6379
      - 36381:26379
    volumes:
      - /data/docker/redis/sentinel/slave2:/data
      - /root/sources/manifests/redis/redis-conf:/usr/local/etc/redis
    environment:
      TZ: "Asia/Shanghai"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 50M
    networks:
      default:
        ipv4_address: "172.18.1.7"

networks:
  default:
    external: true
    name: redis-sentinel
