apiVersion: v1
kind: Service
metadata:
  name: etcd-svc
  namespace: common
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: etcd
    app.kubernetes.io/name: etcd
  ports:
    - name: etcd-2379
      port: 2379
      protocol: TCP
      targetPort: 2379
      nodePort: 32379