apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: common
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - name: mysql-3306
      port: 3306
      protocol: TCP
      targetPort: 3306
      nodePort: 31306