apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
  namespace: common
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: rabbitmq
    app.kubernetes.io/name: rabbitmq
  ports:
    - port: 5672
      protocol: TCP
      targetPort: 5672
      nodePort: 31672

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-dashboard-svc
  namespace: common
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: rabbitmq
    app.kubernetes.io/name: rabbitmq
  ports:
    - port: 15672
      protocol: TCP
      targetPort: 15672

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-dashboard-ingress
  namespace: common
  annotations:
    kubernetes.io/ingress.class: apisix
spec:
  rules:
  - host: rabbitmq.wjjzst.com
    http:
      paths:
      - backend:
          service:
            name: rabbitmq-dashboard-svc
            port:
              number: 15672
        path: /
        pathType: Prefix