apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: common
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redis
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
      nodePort: 31379