apiVersion: v1
kind: Service
metadata:
  name: {{ include "mmp.fullname" . }}
  labels:
    {{- include "mmp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: svc-{{ . }}
      port: {{ . }}
      protocol: TCP
      targetPort: {{ . }}
    {{- end }}
  selector:
    {{- include "mmp.selectorLabels" . | nindent 4 }}
