apiVersion: v1
kind: Service
metadata:
  name: demo1
  namespace: apps
  labels:
    app: demo1
spec:
  type: LoadBalancer
  loadBalancerIP: 10.200.10.159
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: demo1
 
 
---
 
 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1-deployment
  namespace: apps
  labels:
    app: demo1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo1
  template:
    metadata:
      labels:
        app: demo1
    spec:
      containers:
      - name: demo1
        image: mritd/demo
        ports:
          - name: http
            containerPort: 80
            protocol: TCP